### ISSUE TITLE
Divide by zero error causes rotation to become NAN

### ISSUE THREAD

**Issue by Midgard-Public** [kirbyt/KTOneFingerRotationGestureRecognizer#2]
Sometimes the Rotation Gesture recognizer returns NAN as the result of a divide by zero error. It happens here...

```
    CGFloat line1Slope = (line1End.y - line1Start.y) / (line1End.x - line1Start.x);
    CGFloat line2Slope = (line2End.y - line2Start.y) / (line2End.x - line2Start.x);
```

if either of these denominators == 0.0 the rotation property will become NAN which will probably crash whatever app it's being used for. 

I fixed this fairly easily by checking for it first and not updating the rotation for that frame if it would divide by zero.

```
if((line1End.x - line1Start.x) == 0.0 ||  (line2End.x - line2Start.x) == 0.0)
{
    NSLog(@"KTOneFingerRotationGestureRecognizer:: Divide by zero!!!");


}else
{

    CGFloat line1Slope = (line1End.y - line1Start.y) / (line1End.x - line1Start.x);
    CGFloat line2Slope = (line2End.y - line2Start.y) / (line2End.x - line2Start.x);

    CGFloat degs = acosf(((a*c) + (b*d)) / ((sqrt(a*a + b*b)) * (sqrt(c*c + d*d))));

    CGFloat angleInRadians = (line2Slope > line1Slope) ? degs : -degs;
    //////

    [self setRotation:angleInRadians];
}
```

**Comment by Midgard-Public** [comment]
So, the modification I posted earlier didn't quite fix my problem. For some reason the rotation value will keep coming up NAN in certain situations. This is a somewhat simpler fix 

```
    if(!isnan(angleInRadians))
    {
        [self setRotation:angleInRadians];
    }
    else
    {
        NSLog(@"KTOneFingerRotationGestureRecognizer:: Rotation is NAN!!!!");
    }
```

**Comment by sneakygoose** [comment]
replace all of that with this

angleInRadians = atan2f(currentTouchPoint.y - center.y, currentTouchPoint.x - center.x) - 
    atan2f(previousTouchPoint.y - center.y, previousTouchPoint.x - center.x);

Ref: http://www.iphonedevsdk.com/forum/iphone-sdk-development/94378-getting-angle-uiview.html#post391266

**Comment by kirbyt** [comment]
I updated the code with the changed made by Duncan C. It solves the divide by zero issue and simplifies the code.
